<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>브릿지메이커스: 2017년 2월 스키트립 신청현황</title>
  <style>
    button {
      cursor: pointer;
      padding: 10px 20px;
      font-size: 18px;
      margin-bottom: 20px;
    }
    input {
      width: 100%;
      font-size: 14px;
      border: none;
      outline: none;
    }
  </style>
</head>

<body>

<form action="/skitrip-1702/list" method="post">
  <button type="submit">저장</button>
  <table width="100%" cellpadding="5" border="1" cellspacing="0">
    <thead>
    <tr>
      <th width="10%" align="left" valign="top">UID</th>
      <th width="10%" align="left" valign="top">신청일자</th>
      <th width="10%" align="left" valign="top">이름</th>
      <th width="10%" align="left" valign="top">사는City</th>
      <th width="10%" align="left" valign="top">타는것</th>
      <th width="10%" align="left" valign="top">장비유무</th>
      <th width="10%" align="left" valign="top">티켓필요</th>
      <th width="10%" align="left" valign="top">저녁식사참여</th>
      <th width="10%" align="left" valign="top">라이드필요</th>
      <th width="10%" align="left" valign="top">라이드가능</th>
    </tr>
    </thead>

    <tbody>
    <?php $i=0;foreach($data as $row):?>
      <tr>
        <input type="hidden" name="id[<?=$i?>]" value="<?=$row->id?>" />
        <td><?=$row->id?></td>
        <td><?=$row->date?></td>
        <td><input type="text" name="name[<?=$i?>]" value="<?=$row->name?>" /></td>
        <td><input type="text" name="city[<?=$i?>]" value="<?=$row->city?>" /></td>
        <td><input type="text" name="whichRide[<?=$i?>]" value="<?=$row->whichRide?>" /></td>
        <td><input type="text" name="haveEquipment[<?=$i?>]" value="<?=$row->haveEquipment?>" /></td>
        <td><input type="text" name="needTicket[<?=$i?>]" value="<?=$row->needTicket?>" /></td>
        <td><input type="text" name="joinDinner[<?=$i?>]" value="<?=$row->joinDinner?>" /></td>
        <td><input type="text" name="needride[<?=$i?>]" value="<?=$row->needride?>" /></td>
        <td><input type="text" name="canride[<?=$i?>]" value="<?=$row->canride?>" /></td>
      </tr>
      <?php $i++;endforeach;?>
    </tbody>

  </table>
</form>

<div>총 <?=count($data)?>명</div>



</body>