<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>브릿지메이커스: 2016 순모임 신청현황</title>
  <style>
    button {
      cursor: pointer;
      padding: 10px 20px;
      font-size: 18px;
      margin-bottom: 20px;
    }
    input {
      width: 100%;
      font-size: 14px;
      border: none;
      outline: none;
    }
  </style>
</head>

<body>

<form action="/soon-16/list" method="post">
  <button type="submit">저장</button>
  <table width="100%" cellpadding="5" border="1" cellspacing="0">
    <thead>
    <tr>
      <th width="10%" align="left" valign="top">UID</th>
      <th width="10%" align="left" valign="top">신청일자</th>
      <th width="10%" align="left" valign="top">이름</th>
      <th width="10%" align="left" valign="top">나이</th>
      <th width="10%" align="left" valign="top">성별</th>
      <th width="10%" align="left" valign="top">사는곳</th>
      <th width="10%" align="left" valign="top">순신청</th>
      <th width="10%" align="left" valign="top">라이드필요</th>
      <th width="10%" align="left" valign="top">라이드가능</th>
      <th width="10%" align="left" valign="top">참여도</th>
    </tr>
    </thead>

    <tbody>
    <?php $i=0;foreach($data as $row):?>
      <tr>
        <input type="hidden" name="id[<?=$i?>]" value="<?=$row->id?>" />
        <td><?=$row->id?></td>
        <td><input type="text" name="date[<?=$i?>]" value="<?=$row->date?>" /></td>
        <td><input type="text" name="name[<?=$i?>]" value="<?=$row->name?>" /></td>
        <td><input type="text" name="age[<?=$i?>]" value="<?=$row->age?>" /></td>
        <td><input type="text" name="gender[<?=$i?>]" value="<?=$row->gender?>" /></td>
        <td><input type="text" name="address[<?=$i?>]" value="<?=$row->address?>" /></td>
        <td><input type="text" name="register[<?=$i?>]" value="<?=$row->register?>" /></td>
        <td><input type="text" name="needride[<?=$i?>]" value="<?=$row->needride?>" /></td>
        <td><input type="text" name="canride[<?=$i?>]" value="<?=$row->canride?>" /></td>
        <td><input type="text" name="participation[<?=$i?>]" value="<?=$row->participation?>" /></td>
      </tr>
      <?php $i++;endforeach;?>
    </tbody>

  </table>
</form>

<div>총 <?=count($data)?>명</div>



</body>